### ISSUE TITLE
Create New Institution: Status Value Does Not Get Passed Correctly

### ISSUE THREAD

**Issue by swapneelrane** [gitmedha/sis-frontend#304]
**Describe the task**
When creating a new institution, while "Active" looks correctly capitalized on frontend, it show up as "active" in backend.

You'll need to remove code that is changing capitalization for the Status field values

![image](https://user-images.githubusercontent.com/21273738/146026110-0adbb59d-d6b5-40a7-a7fc-bd7ebc6ffb5e.png)

**Comment by rathorevaibhav** [comment]
This is not happening anymore. The institution status is being saved correctly with case sensitivity intact.
