### ISSUE TITLE
Show "Inactive" user status besides username in detail view

### ISSUE THREAD

**Issue by swapneelrane** [gitmedha/sis-frontend#336]
If a user is inactive (i.e. `user.blocked` = True) ... show append (Inactive) to username in Assigned To field:

E.g., below username should appear as: Srestha Bhattacharya (Inactive)

https://sis-staging.medha.org.in/batch/1132
![image](https://user-images.githubusercontent.com/21273738/149062171-714cfbcb-b23d-468f-90b8-1c6efaf88941.png)

This will tell users that they may need to reassign this record to an active user, and that's why the current user name is not appearing in _Assigned To_ list:
![image](https://user-images.githubusercontent.com/21273738/149062430-6dc0efd8-ac32-4caa-87ba-329dddb109d1.png)

**Comment by Kirtigour** [comment]
This is not required right now.
