### ISSUE TITLE
Add checkbox on Program Enrollment page to deactivate Batch lookup field

### ISSUE THREAD

**Issue by swapneelrane** [gitmedha/sis-frontend#412]
1. Add a checkbox field in the student form called `Student Registered Only For Employment Connections`
2. This field will be used to add students to SIS who Medha only supports via employment connections i.e. these students do not attend any Medha program and are not part of a batch
3. The program enrollment section and add/edit program enrollment option will still be visible for these types of students
4. The batch field in the program enrollment form should become inactive and non-mandatory

_NOTE: program enrollment records still need to be created for such students so that we can identify Institution to which they belong_

_NOTE: outdated image below. Refer above steps_

<img width="807" alt="Screenshot 2022-04-15 at 8 41 06 AM" src="https://user-images.githubusercontent.com/21273738/163512480-6188bb57-0439-41df-bfb9-40922604242a.png">

**Comment by Kirtigour** [comment]
Data team has already created batches for PI and we tracking data that way.
