### ISSUE TITLE
'Updated at' field for Employment Connections is incorrect. Showing current date

### ISSUE THREAD

**Issue by Mariamraza15** [gitmedha/sis-frontend#435]
**Describe the task**
In the Employment Connections section in the student profile, the 'Updated At' field shows the current date. 

**Expected behavior**
In the Employment Connections section, the 'Updated At' field should show the date on which the record was updated. Currently, all entries are showing today's date

**References**
Specify any reference material / links -
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/106536464/171382805-267c18ff-6a9d-45d2-bff2-efaa95e9b430.png">

**Comment by Mariamraza15** [comment]
@deepaksharma9dev  I am still able to see today's date in the 'Updated at' field in the Employment Connections module. 
https://sis-staging.medha.org.in/student/84675

**Comment by Kirtigour** [comment]
Hi @deepaksharma9dev, this is looks good and ready for production.

**Comment by Kirtigour** [comment]
This is working fine.
