### ISSUE TITLE
Sort Area and Institution Names on Pehel page

### ISSUE THREAD

**Issue by Mariamraza15** [gitmedha/sis-frontend#436]
**Describe the task**
The following are not sorted on Pehel Page

- [ ] Educational Institution
- [ ] Area
- [ ] Course Level

**Expected behavior**
A clear and concise description of what needs to be done.

**References**
Specify any reference material / links

**Comment by deepaksharma9dev** [comment]
@Mariamraza15 @Kirtigour if it is the issue on the Pehel Page? how can we fix this in the sis codebase? @rathorevaibhav  could you please give an idea?

**Comment by rathorevaibhav** [comment]
Confirmed as working. Closing.
