### ISSUE TITLE
Hyperlink in listing pages for Students, Employers, Opportunities, Institutions should be provided in search bar

### ISSUE THREAD

**Issue by Mariamraza15** [gitmedha/sis-frontend#439]
**Describe the task**
In search bar, when we see list of students, employers, opportunities, etc., we should be able to right-click on them and open them in new tab

**Expected behavior**
A clear and concise description of what needs to be done.

**References**
Specify any reference material / links

**Comment by deepaksharma9dev** [comment]
@Mariamraza15 @Kirtigour  I have added this feature and tested locally as well, Raising a pull request after merging you guys can test it thanks

**Comment by Kirtigour** [comment]
@deepaksharma9dev, this looks good on staging.
