### ISSUE TITLE
After deletion of program enrollment/employment connection => redirect user to student profile

### ISSUE THREAD

**Issue by Mariamraza15** [gitmedha/sis-frontend#442]
**Describe the task**

- [ ] When Program enrollment/Employment Connection is deleted, then it should redirect back to the same student's profile where the deletion was done. 
- [x] When we delete Opportunity within Employers, then it should redirect back to the same employer and not the Employer Main page. 

**Expected behavior**
A clear and concise description of what needs to be done.

**References**
Specify any reference material / links

**Comment by deepaksharma9dev** [comment]
@Mariamraza15  I have tested this and it is working fine, there is no data in the employer tab on stagging that is why not able to replicate it on stagging

**Comment by deepaksharma9dev** [comment]
@Kirtigour sure thing, let me see it. will update about this

**Comment by deepaksharma9dev** [comment]
@Kirtigour @Mariamraza15 it is working fine now, i have tested.

**Comment by deepaksharma9dev** [comment]
@Mariamraza15 @Kirtigour This is deployed in the last production build

**Comment by Kirtigour** [comment]
This is working fine on production.

**Comment by deepaksharma9dev** [comment]
@Mariamraza15 @Kirtigour Please close it as it has deployed and working fine
