### ISSUE TITLE
Alumni services data migration

### ISSUE THREAD

**Issue by rathorevaibhav** [gitmedha/sis-frontend#456]
### Also need to fix #531 once this is complete.

**Describe the task**

**Task 1 - Old SIS alumni services migration**
From Swapneel: I've extract all Alumni Services records to this [CSV file](https://medhacorp-my.sharepoint.com/:x:/g/personal/swapneel_rane_medha_org_in/EdzFpQblK0hLnrr2xXFPj0EBXndJcEXB9ZYLF-yka0MkkQ?e=fh4CNy)

It has 6.9k records. Use the student_id_new_sis field to map Alumni Services records to corresponding Student records:
<img width="1390" alt="Screenshot 2022-06-09 at 12 34 58 PM" src="https://user-images.githubusercontent.com/12053186/172787387-7f2341f1-a886-4da7-87ac-3c4a2fd0af6e.png">

**Task 2 - New SIS alumni services migration**
Data to be shared

**Comment by Mariamraza15** [comment]
[Alumni Services_1.3.23.csv](https://github.com/gitmedha/sis-frontend/files/10860370/Alumni.Services_1.3.23.csv)
@rathorevaibhav  Please find the extract of the Alumni Services data from the old SIS. This has the 'Assigned To' Data that needs to go in the 'Assigned To' within the Alumni Services module. Please let me know if you need any other column for migrating this data.

**Comment by rathorevaibhav** [comment]
hi @Mariamraza15 @Kirtigour 
the data migration is complete. Here are the stats:

1. Total alumni services with empty assigned to before migration: 6971
2. Total alumni services with empty assigned to after migration: 3
3. Total alumni services updated with assigned_to user value: 6968

The last 3 alumni services that did not get updated do no have any student id associated with them.

**Comment by Kirtigour** [comment]
This looks good on SIS. 
Thanks, @rathorevaibhav.
