### ISSUE TITLE
Start Date and End Date should be aligned while adding a record in the Employment Connection.

### ISSUE THREAD

**Issue by Kirtigour** [gitmedha/sis-frontend#537]
While adding a record of Employment connection, the start date and end date should be aligned. Currently, the end date is visible at the bottom, as shared in the screenshot. 

<img width="797" alt="image" src="https://user-images.githubusercontent.com/106536464/202703800-5e0c86db-fd1e-4124-b6b3-631383cc432f.png">

**Comment by Mariamraza15** [comment]
@rohit-sharma-medha  Tested this on staging. Working fine.
