### ISSUE TITLE
Changing a label in student and alumni page from "Medha Champion" to "Medhavi member"

### ISSUE THREAD

**Issue by Rajsnehil** [gitmedha/sis-frontend#547]
**Describe the task**
On the Students and Alumni page, there is a label named 'Medha Champion'. We need to change it to 'Medhavi Member'.

**Expected behavior**
Rename the label from Medha Champion to Medha member. 
We will need to check in our codebase and rename the label coming from the desired file. We might also need to change the strapi-backend if possible.

**Comment by Kirtigour** [comment]
@deepaksharma9dev, The name should be Medhavi Member. The title had a typo, but the description had the correct name. Can you please change it to Medhavi Member.

**Comment by deepaksharma9dev** [comment]
@Kirtigour Hi, Yeah sure ! let me just change it and let you know

**Comment by Mariamraza15** [comment]
@deepaksharma9dev  I have tested this. Looks ok on staging

**Comment by Kirtigour** [comment]
Looks good.
