### ISSUE TITLE
Unable to select the Employer while adding new Opportunity. 

### ISSUE THREAD

**Issue by Kirtigour** [gitmedha/sis-frontend#550]
**Describe the bug**
While adding the opportunity from the opportunity module, Employer is getting selected from the drop-down.

**Comment by rathorevaibhav** [comment]
@Kirtigour this is fixed on staging and ready to test. Please have a look.

**Comment by Kirtigour** [comment]
@rathorevaibhav, this is working fine. You can move this to production.

**Comment by rathorevaibhav** [comment]
@Kirtigour @Mariamraza15 I'm unable to replicate it anymore. Although I faced this issue initially and it seems like it requires certain conditions to be met before we see this error.

I would need some inputs from your end if you're able to replicate and share those steps, I can look more into this issue.

**Comment by Mariamraza15** [comment]
@rathorevaibhav  In the Opportunities module, while editing this on staging, when I click on Edit, I am unable to see the Employer Name. When I close the window and click on Edit again, then I am able to see the Employer Name.

**Comment by rathorevaibhav** [comment]
hi @Mariamraza15 I think this is coming because of the slow speed of the staging site. I just checked at my end and if we wait a bit for page to fully load, then the employer was coming fine in the first go.

Since this is related to speed of the server and as our production environment is much faster, I don't anticipate this issue will come on production. Let me know what you think.

We can target increasing the speed of staging as a separate action item.

**Comment by Mariamraza15** [comment]
Hi @rathorevaibhav, The issue occurs only in the edit mode. I waited for some time, the page was fully loaded but the Employer name didn't appear.

**Comment by Kirtigour** [comment]
@rathorevaibhav, We don't get the empty employer anymore, but I can select any other employer from the dropdown, which shouldn't be the case. 

<img width="489" alt="image" src="https://user-images.githubusercontent.com/106536464/235409264-9c2bebac-4ae1-4ce6-bb15-4951c76a1309.png">

<img width="442" alt="image" src="https://user-images.githubusercontent.com/106536464/235409295-04f00a38-ad3c-468b-9f34-9ffb81357ff9.png">

**Comment by rathorevaibhav** [comment]
This is complete and working as expected. The restriction on employer field from opportunity edit form will be targeted separately after discussion.
