### ISSUE TITLE
Module Access for Chapter Heads ID

### ISSUE THREAD

**Issue by Kirtigour** [gitmedha/sis-frontend#552]
**Describe the task**
There are a few Interns who will be entering the data in the SIS using one ID - chapter.heads@medha.org.in

**Expected behaviour**
1. Student Module- View and edit access
2. Program Enrolment Module - View access
3. Employment Connection Module - View access
4. Alumni Services module - View and edit access
5. They should not be able to delete any record. 

Few more things:
1. Hide CV upload/delete option
2. Hide CV field from edit form
3. Hide add new student button (and form)

**Comment by rathorevaibhav** [comment]
@Mariamraza15 @Kirtigour this is complete and deployed on test site. Please have a look.

One way to test it is:
1. Go to Strapi dashboard for test site
2. Visit users
3. Find your user
4. Change the role to "Chapter Head" and save
5. Go to SIS app and refresh

**Comment by Kirtigour** [comment]
@rathorevaibhav, can you please change my role to Chapter head, as I cannot do it on my end? Once you'll do that, I'll test it. 
Thanks!

**Comment by rathorevaibhav** [comment]
@Kirtigour I've updated your role to Chapter Head.

Also @Mariamraza15 has tested this.

**Comment by Kirtigour** [comment]
@rathorevaibhav, I have tested this. We can now move this to production.

**Comment by Kirtigour** [comment]
This looks good on production.
