### ISSUE TITLE
Add a field to know 'How did you hear about us' on Pehel and SIS.

### ISSUE THREAD

**Issue by Mariamraza15** [gitmedha/sis-frontend#563]
Field to be added on Pehel and SIS called - 'How did you hear about us?' 

Dropdown options:
- Direct pitching
- Campus / Teachers
- Friends
- Online search
- Other 
   - If Other, Specify (text input)

The saved entries should be displayed in student details page, below `Interested in Employment Opportunities` field.

This field needs to be mandatory.

**Comment by rathorevaibhav** [comment]
@Kirtigour @Mariamraza15 this is ready to test

Please use this link to test the staging form for new student registration:
https://medha.org.in/payments/new-register-test.php

**Comment by Mariamraza15** [comment]
@rathorevaibhav I tested this on staging. Cannot see this field in the edit mode or when I click 'Add New Student'

**Comment by rathorevaibhav** [comment]
@Mariamraza15 this is ready to test. I've worked on the feedbacks and the fields should be visible on the SIS student forms.
