### ISSUE TITLE
Block SRM access from being able to edit the Grant field within Batch module. 

### ISSUE THREAD

**Issue by Kirtigour** [gitmedha/sis-frontend#564]
**Describe the task**
SRM should not be able to edit the Grant field within the batch module. It should be set as default to **Not Allocated|None** while creating a new batch. Only Partnership and Data team should be able to edit this field. 

<img width="433" alt="image" src="https://user-images.githubusercontent.com/106536464/223318797-434943e6-c3cf-4dbe-929b-12f79bde42f5.png">

**Proposed solution**
1. Rename the "Basic" role to "SRM"
2. Add a new role named "Partnerships"
3. The grant field should only be editable by Partnerships & Admins. Rest should see a disabled field for them.
4. The field value should be set as default to **Not Allocated|None** when SRMs create a new batch.

**Comment by Kirtigour** [comment]
@rathorevaibhav, this is working fine on staging.

**Comment by Kirtigour** [comment]
@rathorevaibhav, the below-mentioned points still need to be worked on. For me, it's working as an Admin. We still need the role of Partnership here as they will be entering the data in this field. 

Proposed solution

1. Add a new role named "Partnerships."
2. The grant field should only be editable by Partnerships.

**Comment by Mariamraza15** [comment]
@rathorevaibhav I am unable to see the 'Partnerships' role on production Strapi. It is visible only on staging Strapi.

**Comment by rathorevaibhav** [comment]
@Mariamraza15 @Kirtigour the partnership role is now available on production Strapi. Please have a look.

**Comment by Mariamraza15** [comment]
> @Mariamraza15 @Kirtigour the partnership role is now available on production Strapi. Please have a look.

Thank you!

**Comment by Kirtigour** [comment]
@rathorevaibhav, this is working fine on production. Thanks!
