### ISSUE TITLE
New field Mode of Payment to be added under the batch module. 

### ISSUE THREAD

**Issue by Kirtigour** [gitmedha/sis-frontend#581]
A field named **Mode of Payment** is to be added under the Batches module with the dropdown of - 
1. Free 
2. Paid by College
3. Paid by Students

The field needs to be mandatory.

**Comment by rathorevaibhav** [comment]
@rajatsajwan testing feedback:
1. There are no options on staging for mode of payment
<img width="774" alt="image" src="https://user-images.githubusercontent.com/12053186/234278811-a1038817-b56a-4995-8003-efa4fd28a88d.png">

2. The validation is not coming up for the new field. I'm able to save the batch without entering the mode of payment
<img width="781" alt="image" src="https://user-images.githubusercontent.com/12053186/234278282-519994e2-7352-4778-baa3-50f1befdd0a7.png">

**Comment by Kirtigour** [comment]
@rathorevaibhav, I can't see any option in the dropdown. 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/106536464/234765995-dda80feb-1847-4184-a6bf-d4dc2b5fb849.png">

**Comment by rathorevaibhav** [comment]
@Kirtigour this is fixed. Please check again.

**Comment by Kirtigour** [comment]
@rathorevaibhav, this is working fine on Staging.

**Comment by Kirtigour** [comment]
This is working fine.
