### ISSUE TITLE
Employment connection is getting saved without entering the Assigned to (Mandatory field) data. 

### ISSUE THREAD

**Issue by Kirtigour** [gitmedha/sis-frontend#591]
The employment connection record is saved without entering data in the Assigned To field. The Assigned To is mandatory. 

Here is the link to an example - https://sis-new.medha.org.in/student/38987

**Comment by deepaksharma9dev** [comment]
@Kirtigour @Mariamraza15 so what have you decided about this issue?

**Comment by Mariamraza15** [comment]
@deepaksharma9dev I am unable to login to the SIS staging. Not able to test anything

**Comment by Kirtigour** [comment]
@deepaksharma9dev, I don't see any changes made here as well.

**Comment by Mariamraza15** [comment]
This works on staging. @deepaksharma9dev  You can go ahead.
