### ISSUE TITLE
The Fee term to be replaced by Contribution

### ISSUE THREAD

**Issue by Kirtigour** [gitmedha/sis-frontend#592]
The Fee label needs to be changed to Contribution. 

Current Label Name | New Label Name
-- | --
Fee Status | Contribution Status
Fee Amount (INR) | Contribution Amount (INR)
Fee Payment Date | Contribution Payment Date
Fee Refund Date | Contribution Refund Date

Also, while viewing the program enrollment record, only the Transaction ID/Receipt number is visible but while editing/adding it says Fee Transaction ID/Receipt number 

<img width="719" alt="image" src="https://user-images.githubusercontent.com/106536464/232748727-7b3d0baf-e9df-4a11-90e0-4e3bacaebd0c.png">

<img width="771" alt="image" src="https://user-images.githubusercontent.com/106536464/232748893-420f7f7c-ad39-4694-979f-69b90ccc8ee3.png">

**Comment by Kirtigour** [comment]
@deepaksharma9dev, I checked this and I don't think any change were made here. Sharing a screenshot for your reference - 
<img width="673" alt="image" src="https://user-images.githubusercontent.com/106536464/234250061-463e4a0b-2237-45fc-ac49-76af5ed8c531.png">

**Comment by Mariamraza15** [comment]
@deepaksharma9dev  Request you to reword Fee Details to Contribution Details as well.  Thank you 
<img width="525" alt="image" src="https://user-images.githubusercontent.com/106530137/234259243-a5e76c06-4077-4e51-adb9-63d7b2442075.png">

**Comment by Kirtigour** [comment]
@deepaksharma9dev, we missed mentioning in the task above that there is a field **Per Student Fee** under the batch module which needs to be renamed **Per Student Contribution**

Sharing the link to the one of the batch - https://sis-staging.medha.org.in/batch/1238
<img width="788" alt="image" src="https://user-images.githubusercontent.com/106536464/234785611-1af0cd87-4c7c-4448-b6d9-e086fb2b85cb.png">

**Comment by deepaksharma9dev** [comment]
@Kirtigour  I have made this change

**Comment by rathorevaibhav** [comment]
Merged

**Comment by deepaksharma9dev** [comment]
@Kirtigour can you close it ?
