### ISSUE TITLE
Add a column called tier in geographies table in SIS

### ISSUE THREAD

**Issue by Kirtigour** [gitmedha/sis-frontend#597]
Need to add a column via Strapi.

**Comment by deepaksharma9dev** [comment]
@Kirtigour  I have made this change and raised a pull request, @rathorevaibhav will review it and merge it, for staging

**Comment by deepaksharma9dev** [comment]
@Mariamraza15  @Kirtigour  just see if these change is not making any impact on our current features. Thanks

**Comment by Kirtigour** [comment]
@deepaksharma9dev, this looks fine to me.
