### ISSUE TITLE
Add URL field to resources

### ISSUE THREAD

**Issue by Kirtigour** [gitmedha/sis-frontend#601]
We have been publishing our reports as a microsite, and we wanted them to be listed under the resources page>Medha Reports.

The challenge is that we cannot tag pages as resources so that it populates under Medha Reports, as previous reports were uploaded as PDFs. 

In the backend, the resources tab allows us to add a title, excerpt, feature image and a PDF. We want to add a URL field so that we can add an outbound link and redirect traffic to the microsite reports.

**Comment by rathorevaibhav** [comment]
This is working and confirmed on production. Closing.
