### ISSUE TITLE
'Please mention your family's annual income' field on Pehel and SIS

### ISSUE THREAD

**Issue by Mariamraza15** [gitmedha/sis-frontend#619]
- Add a new field on Pehel and SIS - 'Please mention your family's annual income'.
- This field will be an open text box that takes number input
- It should be under 'Family's Annual Income' field.
- Can there be a condition where if someone selects <25,000, then the text box only accepts values less than 25,000?

### Changes to be done
1. Input field to accept only numeric inputs
2. New field on Pehel with validation based on selected radio input
3. New field on SIS frontend student details page below `Income Level (INR)` field
4. New input field on student create and edit form

**Comment by rathorevaibhav** [comment]
This has been moved to JIRA. Closing here.
