### ISSUE TITLE
Cities reflecting twice on Pehel

### ISSUE THREAD

**Issue by Kirtigour** [gitmedha/sis-frontend#629]
**Describe the bug**
There are a few cities on Pehel which are reflecting twice - 
<img width="397" alt="image" src="https://github.com/gitmedha/sis-frontend/assets/106536464/aad3855f-6d71-447b-9cd5-8e7dd52d2b0e">

Also, Jammu & Kashmir doesn't have any city under the dropdown.

**Comment by rathorevaibhav** [comment]
@Kirtigour this is fixed on production. Please check.
